/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@layouts/components/ui/accordion"
import { markdownify } from "@lib/utils/textConverter";

export function FaqAccordion({ faq }) {
  return (
    (<div className="flex min-h-screen">
      <Accordion className="w-full mt-4" collapsible="" type="multiple">
        {faq.map((item, i) => (
          <AccordionItem key={i} value={item}>
            <AccordionTrigger className="text-base font-bold text-left md:text-lg lg:text-2xl hover:underline-none text-primary">
              {markdownify(item.title)}
            </AccordionTrigger>
            <AccordionContent className="text-sm md:text-base lg:text-xl">
              {markdownify(item.answer)}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>)
  );
}
